delete from S_HOME_MANAGER where HM_MAIN_HOME != 'A';
	
delete from S_HOME_AUTHORITY_MANAGER where HM_KEYNO in (
	select A.HM_KEYNO 
	from S_HOME_AUTHORITY_MANAGER A
	left join S_HOME_MANAGER B 
	on A.HM_KEYNO = B.HM_KEYNO 
	WHERE B.HM_KEYNO IS NULL
	GROUP BY A.HM_KEYNO
);

delete from U_USERINFO_SETTING where US_TYPE in (
	select A.US_TYPE 
	from U_USERINFO_SETTING A
	left join S_HOME_MANAGER B 
	on A.US_TYPE = B.HM_KEYNO 
	WHERE B.HM_KEYNO IS NULL
	GROUP BY A.US_TYPE
);

DELETE FROM S_MENU_MANAGER WHERE MN_HOMEDIV_C != 'MN_0000000999';

-- txadmin 계정
DELETE FROM U_USERINFO WHERE UI_KEYNO != 'UI_SFMHO';
DELETE FROM U_USERINFO_MEMBER_AUTHORITY WHERE UI_KEYNO IN (
	SELECT A.UI_KEYNO 
	FROM U_USERINFO_MEMBER_AUTHORITY A
	LEFT JOIN U_USERINFO B 
	ON A.UI_KEYNO = B.UI_KEYNO 
	WHERE B.UI_KEYNO IS NULL
	GROUP BY A.UI_KEYNO
);


DELETE FROM U_USERINFO_RESOURCE_AUTHORITY
WHERE UIA_KEYNO IN (
	SELECT UR.UIA_KEYNO
	FROM U_USERINFO_RESOURCE_AUTHORITY UR
	LEFT JOIN U_USERINFO_AUTHORITY UA
	ON UR.UIA_KEYNO = UA.UIA_KEYNO
	WHERE UA.UIA_KEYNO IS NULL
	GROUP BY UR.UIA_KEYNO
);



-- data delete
DELETE FROM B_BOARD_COLUMN;
DELETE FROM B_BOARD_COLUMN_DATA;
DELETE FROM B_BOARD_COLUMN_DATA_HISTORY;
DELETE FROM B_BOARD_COMMENT;
DELETE FROM B_BOARD_COMMENT_LIKE;
DELETE FROM B_BOARD_INTRO_HTML;
DELETE FROM B_BOARD_MAINMINI;
DELETE FROM B_BOARD_NOTICE;
DELETE FROM B_BOARD_NOTICE_HISTORY;
DELETE FROM B_BOARD_SKIN_PACKAGE;
DELETE FROM B_BOARD_SKIN_TEMPLATE;
DELETE FROM B_BOARD_TYPE;
DELETE FROM S_COMMON_FILE_MAIN;
DELETE FROM S_COMMON_FILE_SUB;
DELETE FROM S_MENU_VIEW_DATA;
DELETE FROM S_MENU_VIEW_DATA_HISTORY;
DELETE FROM S_RESOURCES_MANAGER;
DELETE FROM S_RESOURCES_MANAGER_HISTORY;
DELETE FROM S_RESOURCES_MANAGER_SUB;
DELETE FROM T_APPLICAITON_DISCOUNT_SELECT;
DELETE FROM T_APPLICAITON_MANAGER;
DELETE FROM T_APPLICATION_CHARGE;
DELETE FROM T_APPLICATION_DISCOUNT;
DELETE FROM T_APPLICATION_PARTICIPATE;
DELETE FROM T_APPLICATION_PARTICIPATE_SEAT;
DELETE FROM T_APPLICATION_SCHEDULE_MAIN;
DELETE FROM T_APPLICATION_SCHEDULE_SUB;
DELETE FROM T_APPLICATION_USER;
DELETE FROM T_APPLY_PARTICIPATE_DISCOUNT;
DELETE FROM T_COMMON_QRCODE;
DELETE FROM T_DEPARTMENT_MANAGER;
DELETE FROM T_DEPARTMENT_USER_MANAGER;
DELETE FROM T_GROUP_MANAGER;
DELETE FROM T_GROUP_PARTICIPATE;
DELETE FROM T_GROUP_SCHEDULE_MAIN;
DELETE FROM T_GROUP_SCHEDULE_SUB;
DELETE FROM T_PAGE_RESEARCH_MANAGER;
DELETE FROM T_PAGE_RESEARCH_SKIN;
DELETE FROM T_PAGE_RESEARCH_SKIN_HISTORY;
DELETE FROM T_PLACE_MANAGER;
DELETE FROM T_PLACE_SEATGROUP_MAIN;
DELETE FROM T_PLACE_SEATGROUP_SUB;
DELETE FROM T_POPUPINFO;
DELETE FROM T_POPUPINFO_SKIN;
DELETE FROM T_POPUPINFO_SKIN_HISTORY;
DELETE FROM T_POPUPINFO_SUB;
DELETE FROM T_POPUPZONE_CATEGORY;
DELETE FROM T_POPUPZONE_LIST;
DELETE FROM T_SEARCH_KEYWORD;
DELETE FROM T_SURVEY_MGR;
DELETE FROM T_SURVEY_QUESTION;
DELETE FROM T_SURVEY_QUESTION_OPTION;
DELETE FROM T_SURVEY_RESULT_DATA;
DELETE FROM T_SURVEY_RESULT_MGR;
DELETE FROM T_SURVEY_SKIN;
DELETE FROM T_SURVEY_SKIN_HISTORY;
DELETE FROM T_XML_HISTORY;
DELETE FROM U_USERINFO_WITHDRAW;

delete from U_USERINFO_AUTHORITY where UIA_KEYNO IN ('UIA_KVFQG','UIA_SBNFA');


-- 활동기록 삭제
DELETE FROM T_ACTIVITY_HISTORY;
ALTER TABLE T_ACTIVITY_HISTORY AUTO_INCREMENT=1;

-- AUTO_INCREMENT=1
ALTER TABLE B_BOARD_COLUMN                    AUTO_INCREMENT=1;
ALTER TABLE B_BOARD_COLUMN_DATA               AUTO_INCREMENT=1;
ALTER TABLE B_BOARD_COMMENT                   AUTO_INCREMENT=1;
ALTER TABLE B_BOARD_INTRO_HTML                AUTO_INCREMENT=1;
ALTER TABLE B_BOARD_NOTICE                    AUTO_INCREMENT=1;
ALTER TABLE B_BOARD_NOTICE_HISTORY            AUTO_INCREMENT=1;
ALTER TABLE B_BOARD_SKIN_PACKAGE              AUTO_INCREMENT=1;
ALTER TABLE B_BOARD_SKIN_TEMPLATE             AUTO_INCREMENT=1;
ALTER TABLE S_COMMON_FILE_MAIN                AUTO_INCREMENT=1;
ALTER TABLE S_COMMON_FILE_SUB                 AUTO_INCREMENT=1;
ALTER TABLE T_APPLICAITON_MANAGER             AUTO_INCREMENT=1;
ALTER TABLE T_APPLICATION_CHARGE              AUTO_INCREMENT=1;
ALTER TABLE T_APPLICATION_PARTICIPATE         AUTO_INCREMENT=1;
ALTER TABLE T_APPLICATION_SCHEDULE_MAIN       AUTO_INCREMENT=1;
ALTER TABLE T_APPLICATION_SCHEDULE_SUB        AUTO_INCREMENT=1;
ALTER TABLE T_APPLICATION_USER                AUTO_INCREMENT=1;
ALTER TABLE T_GROUP_MANAGER                   AUTO_INCREMENT=1;
ALTER TABLE T_GROUP_PARTICIPATE               AUTO_INCREMENT=1;
ALTER TABLE T_GROUP_SCHEDULE_MAIN             AUTO_INCREMENT=1;
ALTER TABLE T_GROUP_SCHEDULE_SUB              AUTO_INCREMENT=1;
ALTER TABLE T_SURVEY_MGR                      AUTO_INCREMENT=1;
ALTER TABLE T_SURVEY_QUESTION                 AUTO_INCREMENT=1;
ALTER TABLE T_SURVEY_QUESTION_OPTION          AUTO_INCREMENT=1;
ALTER TABLE T_SURVEY_RESULT_DATA              AUTO_INCREMENT=1;
ALTER TABLE T_SURVEY_RESULT_MGR               AUTO_INCREMENT=1;


-- key = 1
UPDATE S_COMMON_SEQ_CNT SET SQ_CNT=NULL WHERE SQ_TABLE_NM='B_BOARD_MAINMINI';
UPDATE S_COMMON_SEQ_CNT SET SQ_CNT=NULL WHERE SQ_TABLE_NM='S_MENU_VIEW_DATA';
UPDATE S_COMMON_SEQ_CNT SET SQ_CNT=NULL WHERE SQ_TABLE_NM='S_MENU_VIEW_DATA_HISTORY';
UPDATE S_COMMON_SEQ_CNT SET SQ_CNT=NULL WHERE SQ_TABLE_NM='S_RESOURCES_MANAGER';
UPDATE S_COMMON_SEQ_CNT SET SQ_CNT=NULL WHERE SQ_TABLE_NM='S_RESOURCES_MANAGER_HISTORY';
UPDATE S_COMMON_SEQ_CNT SET SQ_CNT=NULL WHERE SQ_TABLE_NM='T_APPLICATION_DISCOUNT';
UPDATE S_COMMON_SEQ_CNT SET SQ_CNT=NULL WHERE SQ_TABLE_NM='T_COMMON_QRCODE';
UPDATE S_COMMON_SEQ_CNT SET SQ_CNT=NULL WHERE SQ_TABLE_NM='T_DEPARTMENT_MANAGER';
UPDATE S_COMMON_SEQ_CNT SET SQ_CNT=NULL WHERE SQ_TABLE_NM='T_DEPARTMENT_USER_MANAGER';
UPDATE S_COMMON_SEQ_CNT SET SQ_CNT=NULL WHERE SQ_TABLE_NM='T_PAGE_RESEARCH_MANAGER';
UPDATE S_COMMON_SEQ_CNT SET SQ_CNT=NULL WHERE SQ_TABLE_NM='T_PAGE_RESEARCH_SKIN';
UPDATE S_COMMON_SEQ_CNT SET SQ_CNT=NULL WHERE SQ_TABLE_NM='T_PAGE_RESEARCH_SKIN_HISTORY';
UPDATE S_COMMON_SEQ_CNT SET SQ_CNT=NULL WHERE SQ_TABLE_NM='T_PLACE_MANAGER';
UPDATE S_COMMON_SEQ_CNT SET SQ_CNT=NULL WHERE SQ_TABLE_NM='T_PLACE_SEATGROUP_MAIN';
UPDATE S_COMMON_SEQ_CNT SET SQ_CNT=NULL WHERE SQ_TABLE_NM='T_PLACE_SEATGROUP_SUB';
UPDATE S_COMMON_SEQ_CNT SET SQ_CNT=NULL WHERE SQ_TABLE_NM='T_POPUPINFO';
UPDATE S_COMMON_SEQ_CNT SET SQ_CNT=NULL WHERE SQ_TABLE_NM='T_POPUPINFO_SKIN';
UPDATE S_COMMON_SEQ_CNT SET SQ_CNT=NULL WHERE SQ_TABLE_NM='T_POPUPINFO_SKIN_HISTORY';
UPDATE S_COMMON_SEQ_CNT SET SQ_CNT=NULL WHERE SQ_TABLE_NM='T_POPUPZONE_CATEGORY';
UPDATE S_COMMON_SEQ_CNT SET SQ_CNT=NULL WHERE SQ_TABLE_NM='T_POPUPZONE_LIST';
UPDATE S_COMMON_SEQ_CNT SET SQ_CNT=NULL WHERE SQ_TABLE_NM='T_SURVEY_SKIN';
UPDATE S_COMMON_SEQ_CNT SET SQ_CNT=NULL WHERE SQ_TABLE_NM='T_SURVEY_SKIN_HISTORY';
UPDATE S_COMMON_SEQ_CNT SET SQ_CNT=NULL WHERE SQ_TABLE_NM='T_XML_HISTORY';
UPDATE S_COMMON_SEQ_CNT SET SQ_CNT=NULL WHERE SQ_TABLE_NM='U_USERINFO_WITHDRAW';
